begin;
insert into auth.users(id) values('20000000-0000-4000-8000-000000000001'),('20000000-0000-4000-8000-000000000002'),('20000000-0000-4000-8000-000000000003');
insert into public.staff_roles(user_id,role) values('20000000-0000-4000-8000-000000000001','admin'),('20000000-0000-4000-8000-000000000002','membership_reviewer'),('20000000-0000-4000-8000-000000000003','super_admin');
insert into public.ecosystem_listings(slug,data,published) values('pending-test-public','{"name":"Published fixture","summary":"Synthetic testing facility","primaryType":"supplier","websiteUrl":"https://example.org"}',true),('pending-test-private','{"name":"Private fixture"}',false);
insert into public.ecosystem_submissions(idempotency_key,payload_hash,kind,target_slug,base_revision,proposed) values('test-private',repeat('a',64),'update','pending-test-private',1,'{}');
create function pg_temp.check_true(value boolean,message text) returns void language plpgsql as $$ begin if value is distinct from true then raise exception 'Assertion failed: %',message; end if; end $$;
create function pg_temp.expect_error(query text,code text) returns void language plpgsql as $$ begin begin execute query; exception when others then if sqlstate=code then return; else raise; end if; end; raise exception 'Expected error %',code; end $$;
set local role anon;
select pg_temp.check_true(not public.ecosystem_edit_pending('pending-test-public'),'no open edit reports false');
select pg_temp.check_true(not public.ecosystem_edit_pending('pending-test-private'),'private listing status remains hidden');
select pg_temp.check_true(not public.ecosystem_edit_pending('does-not-exist'),'unknown listing status remains hidden');
select pg_temp.expect_error('select * from public.ecosystem_submissions','42501');
reset role;
set local role service_role;
select public.receive_ecosystem_submission('20000000-0000-4000-8000-000000000010',repeat('b',64),'update','pending-test-public',1,'{"name":"Updated fixture","summary":"Synthetic edited facility","primaryType":"supplier","websiteUrl":"https://example.org"}',null,null,repeat('b',64)) as receipt \gset
select pg_temp.check_true(public.receive_ecosystem_submission('20000000-0000-4000-8000-000000000010',repeat('b',64),'update','pending-test-public',1,'{}',null,null,repeat('b',64))=:'receipt','same web retry retains receipt while locked');
select pg_temp.expect_error($q$select public.import_ecosystem_submission('github:pending-test-second','update','pending-test-public',1,'{"name":"Second update","summary":"Synthetic second edit","primaryType":"supplier","websiteUrl":"https://example.org"}')$q$,'P0409');
reset role;
set local role anon;
select pg_temp.check_true(public.ecosystem_edit_pending('pending-test-public'),'anonymous visitor sees only pending boolean');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000004',true);
select pg_temp.check_true(public.ecosystem_edit_pending('pending-test-public') and (select count(*)=0 from public.ecosystem_submissions),'member sees boolean but not proposal');
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000002',true);
select pg_temp.check_true(public.ecosystem_edit_pending('pending-test-public') and (select count(*)=0 from public.ecosystem_submissions),'membership staff sees boolean but not proposal');
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
select public.review_ecosystem_submission(:'receipt','needs_info',null,'Follow-up needed',1);
select pg_temp.check_true(public.ecosystem_edit_pending('pending-test-public'),'needs information remains locked');
reset role;
set local role service_role;
select pg_temp.expect_error($q$select public.receive_ecosystem_submission('20000000-0000-4000-8000-000000000011',repeat('c',64),'update','pending-test-public',1,'{"name":"Second update","summary":"Synthetic second edit","primaryType":"supplier","websiteUrl":"https://example.org"}',null,null,repeat('c',64))$q$,'P0409');
reset role;
set local role authenticated;
select public.review_ecosystem_submission(:'receipt','rejected',null,'Not current',1);
select pg_temp.check_true(not public.ecosystem_edit_pending('pending-test-public'),'rejection unlocks edits');
reset role;
set local role service_role;
select public.import_ecosystem_submission('github:pending-test-second','update','pending-test-public',1,'{"name":"Second update","summary":"Synthetic second edit","primaryType":"supplier","websiteUrl":"https://example.org"}') as second_receipt \gset
select pg_temp.check_true(public.import_ecosystem_submission('github:pending-test-second','update','pending-test-public',1,'{"name":"Second update","summary":"Synthetic second edit","primaryType":"supplier","websiteUrl":"https://example.org"}')=:'second_receipt','GitHub retry retains receipt while locked');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000003',true);
select pg_temp.check_true(public.ecosystem_edit_pending('pending-test-public'),'super admin sees same pending status');
select public.review_ecosystem_submission(:'second_receipt','approved',1,null,1);
select pg_temp.check_true(not public.ecosystem_edit_pending('pending-test-public'),'approval unlocks edits');
reset role;
set local role service_role;
select public.import_ecosystem_submission('github:pending-test-third','update','pending-test-public',2,'{"name":"Third update","summary":"Synthetic third edit","primaryType":"supplier","websiteUrl":"https://example.org"}');
reset role;
select pg_temp.check_true((select count(*)=1 from public.ecosystem_submissions where target_slug='pending-test-public' and status in ('pending','needs_info')),'exactly one open update after closing earlier edits');
rollback;
