begin;
select no_plan();
insert into auth.users(id,aud,role,email,email_confirmed_at) values
 ('61000000-0000-4000-8000-000000000001','authenticated','authenticated','delivery@example.test',now()),
 ('61000000-0000-4000-8000-000000000002','authenticated','authenticated','admin-delivery@example.test',now()),
 ('61000000-0000-4000-8000-000000000003','authenticated','authenticated','staff-delivery@example.test',now());
insert into public.staff_roles(user_id,role) values('61000000-0000-4000-8000-000000000002','admin'),('61000000-0000-4000-8000-000000000003','membership_reviewer');
insert into public.basic_onboarding_applications(user_id,full_name,email,phone,linkedin_url,date_of_birth,status)
 values('61000000-0000-4000-8000-000000000001','Synthetic Member','delivery@example.test','+919999999999','https://linkedin.com/in/test','1990-01-01','approved');
insert into public.member_notifications(id,user_id,recipient_id,recipient_email,event_key,kind,expected_status,application_revision,state,lease_token,lease_until)
 select ('61000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'61000000-0000-4000-8000-000000000001','61000000-0000-4000-8000-000000000001','delivery@example.test','delivery:'||i,'approved','approved',1,'sending','61000000-0000-4000-8000-000000000099',now()+interval '2 minutes' from generate_series(10,40) i;
select ok(public.record_member_notification_event('before-finish','provider-one','email.delivered','2026-01-01Z'),'unknown provider event persists before finish');
select is((select count(*)::integer from public.member_notification_events),1,'minimal unmatched event retained');
select ok(public.finish_member_notification('61000000-0000-4000-8000-000000000010','61000000-0000-4000-8000-000000000099','accepted','provider-one'),'finish reconciles earlier webhook');
select is((select delivery_state from public.member_notifications where provider_id='provider-one'),'delivered','early webhook reconciled');
select is((select state from public.member_notifications where provider_id='provider-one'),'accepted','queue acceptance stays distinct');
select ok(not public.record_member_notification_event('before-finish','provider-one','email.delivered','2026-01-01Z'),'exact replay is idempotent');
select throws_ok($$select public.record_member_notification_event('before-finish','provider-other','email.delivered','2026-01-01Z')$$,'22023','Conflicting notification event','event id cannot be rebound');
select ok(public.record_member_notification_event('late-sent','provider-one','email.sent','2026-01-02Z'),'out-of-order lower event recorded');
select is((select delivery_state from public.member_notifications where provider_id='provider-one'),'delivered','newer sent cannot downgrade delivered');
select ok(public.record_member_notification_event('older-bounce','provider-one','email.bounced','2025-12-01Z'),'older stronger event recorded');
select is((select delivery_state from public.member_notifications where provider_id='provider-one'),'bounced','older bounce overrides delivered');
select is((select reason from public.member_notification_suppressions where recipient_email='delivery@example.test'),'bounced','bounce suppresses email');
select ok(public.record_member_notification_event('complaint','provider-one','email.complained','2025-11-01Z'),'complaint recorded');
select ok(public.record_member_notification_event('later-delivered','provider-one','email.delivered','2026-01-03Z'),'later delivery recorded without clearing complaint');
select is((select delivery_state from public.member_notifications where provider_id='provider-one'),'complained','complaint remains strongest');
select is((select reason from public.member_notification_suppressions),'complained','suppression cannot be downgraded');
update public.member_notification_settings set enabled=true,pilot_recipients=array['delivery@example.test'];
select ok(not private.member_notification_eligible(n),'future notification eligibility respects suppression') from public.member_notifications n where id='61000000-0000-4000-8000-000000000011';
update public.member_notifications set state='leased' where id='61000000-0000-4000-8000-000000000011';
select ok(not public.prepare_member_notification('61000000-0000-4000-8000-000000000011','61000000-0000-4000-8000-000000000099'),'suppression blocks prepared send');
update public.member_notifications set state='pending' where id='61000000-0000-4000-8000-000000000012';
select is((select count(*)::integer from public.claim_member_notifications()),0,'suppression blocks claim');
select is((select state from public.member_notifications where id='61000000-0000-4000-8000-000000000012'),'suppressed','blocked claim becomes terminal');
select ok(public.finish_member_notification('61000000-0000-4000-8000-000000000013','61000000-0000-4000-8000-000000000099','accepted','provider-two'),'second acceptance has no invented delivery');
select is((select delivery_state from public.member_notifications where provider_id='provider-two'),'unconfirmed','acceptance remains unconfirmed');
select ok(public.record_member_notification_event('two-sent','provider-two','email.sent','2026-01-01Z'),'sent event recorded');
select is((select delivery_state from public.member_notifications where provider_id='provider-two'),'sent','sent is not delivered');
select ok(public.record_member_notification_event('two-delay','provider-two','email.delivery_delayed','2026-01-02Z'),'delay recorded');
select is((select delivery_state from public.member_notifications where provider_id='provider-two'),'delivery_delayed','delay visible');
select ok(public.record_member_notification_event('two-failed','provider-two','email.failed','2026-01-03Z'),'failure recorded');
select is((select delivery_state from public.member_notifications where provider_id='provider-two'),'failed','failure visible');
select ok(public.record_member_notification_event('two-delivery','provider-two','email.delivered','2026-01-04Z'),'delivery after failure recorded');
select is((select delivery_state from public.member_notifications where provider_id='provider-two'),'failed','failure outranks later delivery');
select ok(public.record_member_notification_event('two-suppressed','provider-two','email.suppressed','2026-01-05Z'),'provider suppression recorded');
select is((select delivery_state from public.member_notifications where provider_id='provider-two'),'suppressed','provider suppression visible');
select throws_ok($$select public.record_member_notification_event('bad','provider','email.opened',now())$$,'22023','Invalid notification event','tracking events excluded');
select throws_ok($$select public.record_member_notification_event('future','provider','email.sent',now()+interval '1 day')$$,'22023','Invalid notification event','future occurrence rejected');
select throws_ok($$select public.record_member_notification_event('',null,'email.sent',now())$$,'22023','Invalid notification event','missing identity rejected');
select ok(not has_table_privilege('authenticated','public.member_notification_events','SELECT'),'events private');
select ok(not has_table_privilege('service_role','public.member_notification_events','INSERT'),'events only writable by RPC');
select ok(not has_function_privilege('authenticated','public.record_member_notification_event(text,text,text,timestamptz)','EXECUTE'),'members cannot forge delivery');
select ok(not has_function_privilege('service_role','private.finish_member_notification(uuid,uuid,text,text)','EXECUTE'),'worker cannot bypass serialization');
select ok(not has_function_privilege('anon','public.list_member_notification_status(integer,text,text)','EXECUTE'),'anonymous cannot view status');
select set_config('request.jwt.claim.sub','61000000-0000-4000-8000-000000000001',true);
select throws_ok($$select public.list_member_notification_status()$$,'42501','Administrator access required','member blocked');
select set_config('request.jwt.claim.sub','61000000-0000-4000-8000-000000000003',true);
select throws_ok($$select public.list_member_notification_status()$$,'42501','Administrator access required','staff blocked');
select set_config('request.jwt.claim.sub','61000000-0000-4000-8000-000000000002',true);
select is((public.list_member_notification_status()->>'total')::integer,31,'admin sees total');
select is(jsonb_array_length(public.list_member_notification_status()->'items'),25,'first page capped');
select is(jsonb_array_length(public.list_member_notification_status(2)->'items'),6,'next page complete');
select is((public.list_member_notification_status(1,'DELIVERY@')->>'total')::integer,31,'search case insensitive');
select is((public.list_member_notification_status(1,'%')->>'total')::integer,0,'search treats wildcard literally');
select is((public.list_member_notification_status(1,'','complained')->>'total')::integer,1,'delivery filter supported');
select is((public.list_member_notification_status(1,'','accepted')->>'total')::integer,2,'queue filter supported');
select ok((public.list_member_notification_status(1,'','complained')->'items'->0->>'suppressed')::boolean,'admin sees suppression');
select ok(not (public.list_member_notification_status()->'items'->0 ? 'provider_id'),'provider identifiers omitted from admin view');
select throws_ok($$select public.list_member_notification_status(0)$$,'22023','Invalid notification filter','invalid page rejected');
select throws_ok($$select public.list_member_notification_status(1,repeat('a',121))$$,'22023','Invalid notification filter','search bounded');
select throws_ok($$select public.list_member_notification_status(1,'','invalid')$$,'22023','Invalid notification filter','filter validated');
delete from public.staff_roles where user_id='61000000-0000-4000-8000-000000000002';
select throws_ok($$select public.list_member_notification_status()$$,'42501','Administrator access required','removed admin loses access immediately');
insert into public.staff_roles(user_id,role) values('61000000-0000-4000-8000-000000000002','super_admin');
select is((public.list_member_notification_status()->>'total')::integer,31,'super admin allowed');
select * from finish();
rollback;
