begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
select is((select count(*)::integer from public.public_equipment_wishlist),4,'four deferred candidates seeded');
select is((select sum(vote_count)::integer from public.public_equipment_wishlist),0,'seeded candidates have zero votes');
select is((select count(*)::integer from public.public_equipment_wishlist where wishlist_status='deferred'),4,'seed candidates are deferred not operating equipment');
select hasnt_column('public','public_equipment_wishlist','requester_email','public wishlist excludes email');
select hasnt_column('public','public_equipment_wishlist','notes','public wishlist excludes private notes');
select hasnt_column('public','public_equipment_wishlist','image_path','public wishlist excludes private object paths');
insert into auth.users(id,email,email_confirmed_at,aud,role) select ('b1000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'wish-'||n||'@example.test',now(),'authenticated','authenticated' from generate_series(1,5)n;
insert into public.basic_onboarding_applications(user_id,full_name,email,phone,linkedin_url,date_of_birth,status)
select id,'Wishlist test',email,'9999999999','https://linkedin.com/in/test','1990-01-01',case when id::text like '%003' then 'pending' else 'approved' end from auth.users where id::text like 'b1000000%';
insert into public.staff_roles(user_id,role) values('b1000000-0000-4000-8000-000000000001','admin'),('b1000000-0000-4000-8000-000000000004','membership_reviewer');
set local role anon;
select is((select count(*)::integer from public.public_equipment_wishlist),4,'anonymous visitors read sanitized published wishlist');
select throws_ok('select * from public.component_requests','42501',null,'anonymous visitors cannot read underlying private requests');
reset role;
select set_config('request.jwt.claims','{"sub":"b1000000-0000-4000-8000-000000000003","role":"authenticated"}',true);
select throws_ok($$select public.submit_equipment_wish('Test equipment','A sufficiently detailed project use case')$$,'42501','Approved basic membership required','sign-in alone cannot submit');
select set_config('request.jwt.claims','{"sub":"b1000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select set_config('test.wish',public.submit_equipment_wish('Camera rig','Research camera tracking and localization','Vision','https://example.test/camera',1,'unknown','Model one')::text,true);
select is((select count(*)::integer from public.public_equipment_wishlist where id=current_setting('test.wish')::uuid),0,'new member request stays private pending moderation');
set local role authenticated;
select is((select count(*)::integer from public.my_equipment_wishlist where id=current_setting('test.wish')::uuid),1,'member can read own pending request');
select is((select count(*)::integer from public.component_requests where id=current_setting('test.wish')::uuid),0,'owner cannot read underlying internal moderation notes');
select hasnt_column('public','my_equipment_wishlist','decision_note','own view excludes private moderation note');
select throws_ok($$select public.moderate_equipment_wish(current_setting('test.wish')::uuid,true,'open','Publish')$$,'42501','Website Admin required','member cannot moderate');
select throws_ok($$select public.vote_component_request(current_setting('test.wish')::uuid)$$,'P0002','Published open wishlist item required','unpublished item cannot receive votes');
reset role;
select set_config('request.jwt.claims','{"sub":"b1000000-0000-4000-8000-000000000004","role":"authenticated"}',true);
set local role authenticated;
select is((select count(*)::integer from public.component_requests where id=current_setting('test.wish')::uuid),0,'membership Staff cannot read others wishlist requests');
select throws_ok($$select public.moderate_equipment_wish(current_setting('test.wish')::uuid,true,'open','Publish')$$,'42501','Website Admin required','membership Staff cannot moderate');
reset role;
select set_config('request.jwt.claims','{"sub":"b1000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$select public.moderate_equipment_wish(current_setting('test.wish')::uuid,true,'open','Reviewed for publication')$$,'Admin can publish request');
select throws_ok($$select public.set_component_request_status(current_setting('test.wish')::uuid,'declined','Legacy bypass')$$,'P0002','verified request not found','legacy moderation cannot alter wishlist scope');
select is((select count(*)::integer from public.audit_events where entity_id=current_setting('test.wish')::uuid and action='equipment_wishlist.moderated'),1,'moderation records audit');
select set_config('request.jwt.claims','{"sub":"b1000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select is(public.vote_component_request(current_setting('test.wish')::uuid),1,'approved basic member supports without paid membership');
select is(public.vote_component_request(current_setting('test.wish')::uuid),1,'repeated vote is idempotent');
select is(public.vote_component_request(current_setting('test.wish')::uuid,false),0,'member withdraws own vote');
select is(public.vote_component_request(current_setting('test.wish')::uuid),1,'member can support again');
select set_config('test.second',public.submit_equipment_wish('Other camera','Another camera proposal to merge')::text,true);
insert into public.equipment_wishlist_image_cleanup(object_path,queued_at) values(current_setting('test.second')||'/b2000000-0000-4000-8000-000000000001.png',now()+interval '1 hour');
select is(public.finish_equipment_wish_image(current_setting('test.second')::uuid,auth.uid(),current_setting('test.second')||'/b2000000-0000-4000-8000-000000000001.png','image/png'),null::text,'first scanned image attachment has no previous object');
select is((select count(*)::integer from public.equipment_wishlist_image_cleanup where object_path like current_setting('test.second')||'/%'),0,'attachment atomically clears provisional orphan queue');
select throws_ok($$select public.finish_equipment_wish_image(current_setting('test.second')::uuid,auth.uid(),current_setting('test.second')||'/b2000000-0000-4000-8000-000000000002.webp','image/webp')$$,'22023','Unexpired image upload reservation required','missing upload reservation cannot attach');
insert into public.equipment_wishlist_image_cleanup(object_path,queued_at) values(current_setting('test.second')||'/b2000000-0000-4000-8000-000000000002.webp',now()-interval '1 second');
select throws_ok($$select public.finish_equipment_wish_image(current_setting('test.second')::uuid,auth.uid(),current_setting('test.second')||'/b2000000-0000-4000-8000-000000000002.webp','image/webp')$$,'22023','Unexpired image upload reservation required','expired upload cannot race cleanup to attach');
select is((select count(*)::integer from public.claim_equipment_wish_images(100) where object_path like current_setting('test.second')||'/%'),1,'worker claims due image');
select is((select count(*)::integer from public.claim_equipment_wish_images(100) where object_path like current_setting('test.second')||'/%'),0,'active claim prevents duplicate worker');
update public.equipment_wishlist_image_cleanup set claimed_at=now()-interval '11 minutes' where object_path like current_setting('test.second')||'/%';
select is((select count(*)::integer from public.claim_equipment_wish_images(100) where object_path like current_setting('test.second')||'/%'),1,'stale cleanup claim is recoverable');
update public.equipment_wishlist_image_cleanup set queued_at=now()+interval '1 hour' where object_path like current_setting('test.second')||'/%';
select throws_ok($$select public.finish_equipment_wish_image(current_setting('test.second')::uuid,auth.uid(),current_setting('test.second')||'/b2000000-0000-4000-8000-000000000002.webp','image/webp')$$,'22023','Unexpired image upload reservation required','claimed image cannot attach even with future deadline');
update public.equipment_wishlist_image_cleanup set claimed_at=null where object_path like current_setting('test.second')||'/%';
select ok(not has_function_privilege('authenticated','public.claim_equipment_wish_images(integer)','EXECUTE'),'cleanup claiming is service-only');
select is(public.finish_equipment_wish_image(current_setting('test.second')::uuid,auth.uid(),current_setting('test.second')||'/b2000000-0000-4000-8000-000000000002.webp','image/webp'),current_setting('test.second')||'/b2000000-0000-4000-8000-000000000001.png','replacement returns previous image path');
select is((select count(*)::integer from public.equipment_wishlist_image_cleanup where object_path like current_setting('test.second')||'/%'),1,'previous image atomically queued for deletion');
select ok(not has_function_privilege('authenticated','public.finish_equipment_wish_image(uuid,uuid,text,text)','EXECUTE'),'members cannot mark arbitrary images scanned');
select ok(not has_table_privilege('authenticated','public.equipment_wishlist_image_cleanup','SELECT'),'cleanup queue is private');
select throws_ok($$select public.finish_equipment_wish_image(current_setting('test.second')::uuid,auth.uid(),'wrong/path.png','image/png')$$,'22023','Valid scoped image path required','image attachment prevents cross-item paths');
select set_config('request.jwt.claims','{"sub":"b1000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select public.moderate_equipment_wish(current_setting('test.second')::uuid,true,'open','Publish second');
select set_config('request.jwt.claims','{"sub":"b1000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select public.vote_component_request(current_setting('test.second')::uuid);
select throws_ok($$select public.finish_equipment_wish_image(current_setting('test.second')::uuid,auth.uid(),current_setting('test.second')||'/b2000000-0000-4000-8000-000000000003.jpg','image/jpeg')$$,'42501','Own unpublished wishlist item required','published image cannot be swapped after moderation');
select set_config('request.jwt.claims','{"sub":"b1000000-0000-4000-8000-000000000005","role":"authenticated"}',true);
select public.vote_component_request(current_setting('test.second')::uuid);
select set_config('request.jwt.claims','{"sub":"b1000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
select lives_ok($$select public.merge_equipment_wishes(current_setting('test.second')::uuid,current_setting('test.wish')::uuid,'Same equipment request')$$,'Admin can merge duplicates');
select is((select vote_count from public.public_equipment_wishlist where id=current_setting('test.wish')::uuid),2,'merged votes deduplicate by member');
select is((select count(*)::integer from public.public_equipment_wishlist where id=current_setting('test.second')::uuid),0,'merged source disappears from public view');
select is((select count(*)::integer from public.audit_events where entity_id=current_setting('test.second')::uuid and action='equipment_wishlist.merged'),1,'merge records audit');
update public.basic_onboarding_applications set status='revoked' where user_id='b1000000-0000-4000-8000-000000000002';
select set_config('request.jwt.claims','{"sub":"b1000000-0000-4000-8000-000000000002","role":"authenticated"}',true);
select throws_ok($$select public.vote_component_request(current_setting('test.wish')::uuid,false)$$,'42501','Approved basic membership required','revoked member loses mutation access immediately');
select throws_ok($$select public.submit_equipment_wish('After revoke','This should not be accepted anymore')$$,'42501','Approved basic membership required','revoked member cannot submit');
select set_config('request.jwt.claims','{"sub":"b1000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$update public.component_requests set is_published=true where id=current_setting('test.wish')::uuid$$,'42501',null,'Admin cannot directly publish outside audited RPC');
select throws_ok($$update public.component_requests set image_path='fake.png' where id=current_setting('test.wish')::uuid$$,'42501',null,'Admin cannot directly attach unscanned path');
select throws_ok($$insert into public.component_request_votes(request_id,member_id) values(current_setting('test.wish')::uuid,'b1000000-0000-4000-8000-000000000003')$$,'42501',null,'Admin cannot forge member votes');
reset role;
select throws_ok($$select public.moderate_equipment_wish(current_setting('test.wish')::uuid,true,'available','Ready')$$,'22023','Available equipment needs a catalogue link','Available requires real catalogue entry');
select public.moderate_equipment_wish(current_setting('test.wish')::uuid,true,'available','Ready',null,(select slug from public.components limit 1));
select throws_ok($$select public.moderate_equipment_wish(current_setting('test.wish')::uuid,true,'available','Clear link',null,'')$$,'22023','Available equipment needs a catalogue link','Available cannot clear an existing catalogue link');
select public.moderate_equipment_wish(current_setting('test.wish')::uuid,true,'under_review','Internal only','Public status explanation');
select is((select public_note from public.public_equipment_wishlist where id=current_setting('test.wish')::uuid),'Public status explanation','explicit public explanation is separate from private moderation note');
select is((select merged_into from public.public_equipment_wishlist_redirects where id=current_setting('test.second')::uuid),current_setting('test.wish')::uuid,'public merged id resolves to published canonical request');
select lives_ok($$select public.edit_equipment_wish(current_setting('test.wish')::uuid,'Reviewed camera','Reviewed public camera use case','Vision',null,2,'unknown','Reviewed model')$$,'Admin can edit sanitized public fields');
select is((select component_name from public.public_equipment_wishlist where id=current_setting('test.wish')::uuid),'Reviewed camera','edited title appears in published view');
select is((select count(*)::integer from public.audit_events where entity_id=current_setting('test.wish')::uuid and action='equipment_wishlist.edited'),1,'Admin edit is audited');
select set_config('request.jwt.claims','{"sub":"b1000000-0000-4000-8000-000000000004","role":"authenticated"}',true);
select throws_ok($$select public.edit_equipment_wish(current_setting('test.wish')::uuid,'Wrong editor','Unauthorized edit attempt text','Other',null,1,'unknown',null)$$,'42501','Website Admin required','membership Staff cannot edit requests');
set local role service_role;
select lives_ok('select image_path,image_content_type,is_published,requester_user_id from public.component_requests limit 1','image service can read request authorization fields');
select lives_ok('select role from public.staff_roles limit 1','image service can verify administrator role');
reset role;
select * from finish();
rollback;
