DatabaseDirectory /var/lib/clamav
TCPSocket 3310
TCPAddr 0.0.0.0
Foreground yes
LogClean no
LogVerbose no
ExtendedDetectionInfo no
StreamMaxLength 5M
MaxScanSize 20M
MaxFileSize 5M
MaxRecursion 8
MaxFiles 100
MaxScanTime 15000
MaxThreads 1
MaxQueue 4
ReadTimeout 20
CommandReadTimeout 20
SendBufTimeout 20000
AlertExceedsMax yes
FailIfCvdOlderThan 3
TemporaryDirectory /tmp
